#!/bin/bash

tmp_file=$(mktemp)
termite --class="__text_scratchpad" -e "nvim -c startinsert -c 'setlocal spell' ${tmp_file}" && xclip -selection clipboard < $tmp_file
# termite --class="__text_scratchpad" -e $SHELL -c "sleep 0.1 && nvim -c startinsert -c 'setlocal spell' ${tmp_file}" && xclip -selection clipboard < $tmp_file
